[package]
name = "myr-wire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
myr-core.workspace = true
serde_json.workspace = true
ciborium.workspace = true
blake3.workspace = true
unicode-normalization.workspace = true
hex.workspace = true

[lints]
workspace = true
